Neovici/cosmoz-router

cosmoz-page-route.html
cosmoz-page-router.html

Requesting review on this in order to merge with master.

Replacing content with slot. Refs #15934

---

.eslintignore
.gitignore
.travis.yml
analysis.json
bower.json
cosmoz-page-route.html
cosmoz-page-router.js
package.json
polymer.json
test/.eslintrc.json
test/basic.html
test/index.html
yarn.lock

Hybrid 2.0 element

---

.codeclimate.yml
.eslintrc.json
analysis.json
cosmoz-page-location.html
cosmoz-page-router.js
cosmoz-template-view.js
package.json
test/basic.html
yarn.lock

* Polymer.dom(this).flush undefined
* remove Object.assign polyfill
* Update eslint, codeclimate, yarn deps, analyz

Polymer.dom(this).flush is undefined in 2.x

---

cosmoz-page-router.js

Fire hash-change on cosmoz-route-hash-params-changed

---

cosmoz-page-location.html
test/location.html

routeQuery should be added before routeHash
fixes #20

routeQuery should be added before routeHash

---

cosmoz-page-router.js

Add removeRoute, refresh and activeRoute getter

Add removeRoute, refresh and activeRoute getter

---

.codeclimate.yml
.eslintignore
.gitignore
.travis.yml
analysis.json
cosmoz-page-route.js
cosmoz-page-router-behavior-utilities.js
cosmoz-page-router.js
package.json
wct.conf.json
yarn.lock

fixes https://github.com/Neovici/cosmoz-page-router/issues/26

Tests code coverage, code climate v2

---

cosmoz-page-router.js

call Polymer.flush in 2.x

---

.travis.yml
cosmoz-page-location.html
cosmoz-page-route.html
cosmoz-page-route.js
cosmoz-page-router-behavior-utilities.js
cosmoz-page-router.html
cosmoz-page-router.js
polymer.json
test/basic.html
test/location.html

Update to Polymer 2.x - part 2.
* Replacing var with const and let.
* Simplifying function declarations.
* Switch to polymer-2 linting ruleset
* Updating imports.
Issue is #38.

38 - Update to Polymer 2.x - part 2

---

cosmoz-page-location.html
cosmoz-page-route.js
cosmoz-page-router-behavior-utilities.js
cosmoz-page-router.html
cosmoz-page-router.js
package-lock.json
test/basic.html
wct.conf.json
yarn.lock

Update to Polymer 2.x - part 5.
* Replacing Polymer.dom.
Issue is #38.

38 - Update to Polymer 2.x - part 5

---

cosmoz-page-location.html

Adds `routeChange` observers dynamically after first reading app hash

Adds routeChange observers dynamically after first reading it

---

cosmoz-page-router.html
cosmoz-page-router.js
detect-import-node-bug.html

This reverts commit 8b57f3c31861afc301f1f1e759a8bc361837e338.
> Conflicts:
>	cosmoz-page-router.js
>	detect-import-node-bug.html
Fixes #46

Revert "fixes #3 by using suggested workaround in Polymer issue #2157."

---

cosmoz-page-router.js

Fixes production errors

---

README.md

forgot to trigger initial semantic release

fix(readme): missing depfu badge

---

package-lock.json
package.json

semantic-release config update

chore: semantic-release config update

---

lib/use-routes.js

Use correct context in history.pushState(replaceState)
Notify using queueMicrotask

fix: correct context in history.pushState(replaceState)

---

.github/karma-problem-matcher.json
.github/workflows/workflow.yml
cosmoz-page-router.js
lib/use-routes.js
package-lock.json
package.json
test/basic.test.js

Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>

fix: npm packaging, eslint/karma problem matchers, deps upgrade

---

lib/use-hash-param.js

Adds hash param setter support

feat(hash-param)!: add setter support

---

package-lock.json
package.json

feat: update deps

---

lib/use-hash-param.js

fix(use-hash-param): fix wrong url in setter

---

lib/use-hash-param.js

Sets param state only when param has actually changed.

fix(use-hash-param): setState only when changed

---

.github/workflows/workflow.yml

Run Github actions  on beta branch

chore(ci): run gha on beta branch

---

CREDITS.md
README.md
package.json
stories/cosmoz-router.stories.js
test/basic.test.ts

BREAKING CHANGE: rename module and repo

feat: rename

---

src/use-route-events.ts
src/use-router.ts

feat(use-router): adjust Route handle type def

---

src/match.ts

feat(match): access original route object

---

src/index.ts
src/load.ts
src/match.ts
src/use-routes.ts
test/basic.test.ts

Add dynamic import load helper

feat: add dynamic import load helper

---

src/match.ts
src/use-router.ts

Improve inference in the type def of useRoutes and as useRouter.

feat(router): improve type def

---

package-lock.json
package.json
src/load.ts
src/router.ts
src/use-hash-param.ts
src/use-route-events.ts
src/use-router.ts
src/use-routes.ts
stories/cosmoz-router.stories.js
stories/views/home.js
stories/views/param-reading-view.js
stories/views/view-1.js
stories/views/view-2.js
stories/views/view-3.js
test/basic.test.ts

BREAKING CHANGE: Upgrade to @pionjs/pion

feat: update to pion

---

.husky/commit-msg
package-lock.json
package.json
test/basic.test.ts

chore(deps): upgrade

---

package-lock.json
package.json

Reverts Neovici/cosmoz-router#175

Revert "chore(deps-dev): bump storybook from 8.6.14 to 9.1.1"
